In [10]:
import numpy as np


In [11]:
arr, b = [], []
with open('matrix.txt', 'r') as f:
    for l in f.readlines():
        tmp = l.split("|")
        b.append(int(tmp[1].rstrip()))
        arr.append([int(n) for n in ''.join(tmp[0].split())])
        del tmp
    arr, b = np.array(arr), np.array(b)
n,m = arr.shape
print(n,m)
print(arr)
print(sum(list(arr[i][j] for i in range(0, n) for j in range(0, m) if i == j)))


5 7
[[1 0 0 2 3 4 5]
 [2 1 0 0 4 5 5]
 [2 4 1 0 0 7 8]
 [1 3 6 1 1 1 3]
 [1 6 7 8 1 1 2]]
5


In [14]:
s = sum(arr[i][j] for i in range(0, n) for j in range(0, m) if i != j)
z = [arr[i][j] for i in range(0, n) for j in range(0, m) if i == j and arr[i][j] >= s and arr[i][j] > 0 ]
A1 = np.zeros((n, m))
print(A1)


if len(z):
    pass
    
#          if (z = 0) then
#            begin
#              for i := 1 to n do
#                begin
#                  for j := 1 to n do
#                    if (i = j) then
#                      A1[i, j] := 0
#                    else
#                      A1[i, j] := -(A[i, j]/A[i, i]);
#                  b1[i] := b[i]/A[i, i];
#                end;

#              for i := 1 to n do
#                X0[i] := b1[i];
#              k := 0;
#              repeat
#                max := 0;
#                for i := 1 to n do
#                  begin
#                    S := 0;
#                    for j := 1 to n do
#                      S := S + A1[i, j] * X0[j];
#                    X[i] := b1[i] + S;
#                  end;

#                for i := 1 to n do
#                  begin
#                    if (abs(X[i]-X0[i]) > max) then
#                      max := abs(X[i]-X0[i]);
#                    X0[i] := X[i];
#                  end;
#                k := k + 1;
#              until (max < 0.0001) or (k > 100);


#              Memo1.Lines[0] := '³äïîâ³äü:';
#              for i := 1 to n do
#                Memo1.Lines.Add('X[' + IntToStr(i) + '] = ' + FloatToStr(X[i]));
#            end
#          else

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


In [5]:
if np.linalg.det(arr) !=0:
    pass
else:
    print("det=0:(")

SyntaxError: invalid syntax (<ipython-input-12-7e2f8f2d309f>, line 2)

In [5]:
119-33

86